### PR TITLE
Latest kibana version, use bundled config file, configurable ES host

### PR DESCRIPTION
**Pull request by kim0**
Tested on Ubuntu 12.04 with puppet 3.1

### CODE REVIEW

**Comment by garethr** [comment]
Thanks for this pull request. A few problems I'm afraid. 
- Currently the tests fail for this branch, see https://travis-ci.org/garethr/garethr-kibana/builds/4864470
- I'm not sold on having this module install bundler itself, it makes using it direct from the forge harder. This should be an include or require another module
- Using file_line is a good idea, however it's part of stdlib which isn't currently marked as a dependency in the Modulefile. I'm happy to see that added however

If you need a hand, or you're not sure what I'm getting at let me know

**Comment by kim0** [comment]
Cool, I'll get around to this in a day or two. I think I'll be using
http://forge.puppetlabs.com/ploperations/bundler and adding it and stdlib
as dependencies. Thanks

On Mon, Feb 25, 2013 at 12:27 AM, Gareth Rushgrove <notifications@github.com

**Comment by garethr** [comment]
@kim0 thanks, that sounds like a good plan.

Regarding checking the tests, you should be able to run them locally with bundle install, bundle exec rake spec. Travis then runs them across lots of different ruby and puppet version options. 

You can see the results of that at https://travis-ci.org/garethr/garethr-kibana

Any questions let me know, and thanks again

**Comment by garethr** [comment]
While at monitorama I took a run at this module again and have addressed all the issues here (I think), mainly using other module dependencies

**Pull request closed without merging**
